apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: key-only-artifacts-
spec:
  entrypoint: amlp
  templates:
    - name: amlp
      container:
        image: ppalmes/amlp:latest
        command: [bash, -c]
        args: ["julia --project main_parse.jl /tmp/file/iris.csv > /mnt/file"]
      inputs:
        artifacts:
          - name: file
            path: /tmp/file/
            s3:
              key: csv/
      outputs:
        artifacts:
          - name: ofile
            path: /mnt/file
            s3:
              key: output/output.txt
