apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argparse-key-
spec:
  entrypoint: run-main
  templates:
  - name: run-main
    steps:
    - - name: low-complexity-regression
        template: function-amlp
        arguments:
          parameters:
          - name: complexity
            value: low
          - name: input
            value: iris_reg.csv
          - name: output
            value: low_regression.tgz
          - name: predictiontype
            value: regression
          - name: folds
            value: 2 
          - name: workers
            value: 5
      - name: high-complexity-regression
        template: function-amlp
        arguments:
          parameters:
          - name: input
            value: iris_reg.csv
          - name: predictiontype
            value: regression
          - name: complexity
            value: high
          - name: output
            value: high_regression.tgz
          - name: folds
            value: 2 
          - name: workers
            value: 5
      - name: low-complexity-classification
        template: function-amlp
        arguments:
          parameters:
          - name: input
            value: iris.csv
          - name: predictiontype
            value: classification
          - name: complexity
            value: low
          - name: output
            value: high_regression.tgz
          - name: folds
            value: 2 
          - name: workers
            value: 5
      - name: high-complexity-classification
        template: function-amlp
        arguments:
          parameters:
          - name: input
            value: iris.csv
          - name: predictiontype
            value: classification
          - name: complexity
            value: high
          - name: output
            value: high_regression.tgz
          - name: folds
            value: 2 
          - name: workers
            value: 5
  # ----------
  - name: function-amlp
    inputs:
      parameters:
        - name: complexity
        - name: input
        - name: output
        - name: predictiontype
        - name: folds
        - name: workers
      artifacts:
        - name: file
          path: /inputfile
          s3:
            key: csv/
    container:
      image: ppalmes/automlpipeline:latest
      command: 
      args: 
        - "-t{{inputs.parameters.predictiontype}}"
        - "-c{{inputs.parameters.complexity}}"
        - "-f{{inputs.parameters.folds}}"
        - "-w{{inputs.parameters.workers}}"
        - "-o/outputfile"
        - "/inputfile/{{inputs.parameters.input}}"
    outputs:
      artifacts:
        - name: ofile
          path: /outputfile
          s3:
            key: "output/{{inputs.parameters.output}}"
