apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: amlp-
spec:
  entrypoint: run-automl
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: my-existing-volume
      
  arguments:
    parameters:
    - name: args
      value: iris.csv 

  templates:
  - name: run-automl
    inputs:
      parameters:
      - name: args       # parameter declaration
    container:
      # run cowsay with that message input parameter as args
      image: ppalmes/amlp:latest
      command: ["julia", "--project","main_parse.jl"]
      args: ["/volume/csv/{{inputs.parameters.args}}"]
      volumeMounts:
        - name: workdir
          mountPath: /volume
