apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: amlp-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: run-automl
  arguments:
    parameters:
    - name: args
      value: main_parse.jl iris.csv 

  templates:
  - name: run-automl
    inputs:
      parameters:
      - name: args       # parameter declaration
    container:
      # run cowsay with that message input parameter as args
      image: ppalmes/amlp:latest
      command: ["julia", "--project"]
      args: ["{{inputs.parameters.args}}"]
