apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: combine-workflow-template
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  templates:
    - name: run-automl
      inputs:
        parameters:
        - name: args       # parameter declaration
      container:
        image: ppalmes/automlpipeline:latest
        command: ["julia", "--project", "main.jl"]
        args: ["{{inputs.parameters.args}}"]

    - name: run-amlp
      inputs:
        parameters:
        - name: args       # parameter declaration
      container:
        image: ppalmes/amlp:latest
        command: ["julia", "--project","-e",'using Pkg; using AMLPipelineBase; Pkg.test("AMLPipelineBase")']
        args: ["{{inputs.parameters.args}}"]

    - name: run-tsml
      inputs:
        parameters:
        - name: args       # parameter declaration
      container:
        image: ppalmes/amlp:latest
        command: ["julia", "--project","-e",'using Pkg; using TSML; Pkg.test("TSML")']
        args: ["{{inputs.parameters.args}}"]

    - name: run-rust-ml
      inputs:
        parameters:
        - name: args       # parameter declaration
      container:
        image: ppalmes/rust-ml:latest
        command: ["automl"]
        args: ["{{inputs.parameters.args}}"]

    - name: run-autosklearn
      container:
        image: ppalmes/autosklearn-ml:latest
        command: ["python3"]
        args: ["script.py"]

    - name: run-r-ml
      container:
        image: ppalmes/r-ml:latest

    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command: [echo,"{{inputs.parameters.message}}"]
