apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: run-from-combine-workflow-template-
spec:
  entrypoint: run-parallel-automl
  templates:
  - name: run-parallel-automl
    steps:
    - - name: Imputation
        templateRef:
          name: combine-workflow-template
          template: echo
        arguments:
          parameters: [{name: message, value: Imputation}]
    - - name: Normalization
        templateRef:
          name: combine-workflow-template
          template: echo
        arguments:
          parameters: [{name: message, value: Normalization}]
    - - name: FeatureExtraction
        templateRef:
          name: combine-workflow-template
          template: echo
        arguments:
          parameters: [{name: message, value: FeatureExtraction}]
    - - name: FeatureEngineering
        templateRef:
          name: combine-workflow-template
          template: echo
        arguments:
          parameters: [{name: message, value: FeatureEngineering}]
    - - name: nrun-automl
        templateRef:
          name: combine-workflow-template
          template: run-automl
        arguments:
          parameters:
            - name: args
              value: run automl

      - name: nrun-amlp
        templateRef:
          name: combine-workflow-template
          template: run-amlp
        arguments:
          parameters:
            - name: args
              value: run amlp

      - name: nrun-tsml
        templateRef:
          name: combine-workflow-template
          template: run-tsml
        arguments:
          parameters:
            - name: args
              value: run tsml 

      - name: nrun-rust-ml
        templateRef:
          name: combine-workflow-template
          template: run-rust-ml
        arguments:
          parameters:
            - name: args
              value: run rustml

      - name: nrun-autosklearn
        templateRef:
          name: combine-workflow-template
          template: run-autosklearn

      - name: nrun-r-ml
        templateRef:
          name: combine-workflow-template
          template: run-r-ml
