apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-rust-ml-
spec:
  entrypoint: diamond
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: run-rust-ml
    inputs:
      parameters:
        - name: args
    container:
      image: ppalmes/rust-ml:latest
      command: ["automl"]
      args: ["{{inputs.parameters.args}}"]

  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: rust-ml 
        dependencies: [B, C]
        template: run-rust-ml
        arguments:
          parameters: [{name: args, value: run rustml}]
