apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-automl-
spec:
  entrypoint: run-main
  arguments:
    parameters:
    - name: args
      value: run parallel_automl 
  templates:
  - name: run-amlp
    inputs:
      parameters:
      - name: args       # parameter declaration
    container:
      image: ppalmes/amlp:latest
      command: ["julia", "--project","-e",'using Pkg; using AMLPipelineBase; Pkg.test("AMLPipelineBase")']
      args: ["{{inputs.parameters.args}}"]

  - name: run-rust-ml
    inputs:
      parameters:
      - name: args       # parameter declaration
    container:
      image: ppalmes/rust-ml:latest
      command: ["automl"]
      args: ["{{inputs.parameters.args}}"]

  - name: run-autosklearn
    container:
      image: ppalmes/autosklearn-ml:latest
      command: ["python3"]
      args: ["script.py"]

  - name: run-r-ml
    container:
      image: ppalmes/r-ml:latest

  - name: echo
    inputs:
      parameters:
        - name: message
    container:
      image: alpine:3.7
      command: [echo,"{{inputs.parameters.message}}"]

#####
  - name: run-main
    inputs:
      parameters:
      - name: args       # parameter declaration
    steps:
    - - name: extract-data
        template: echo
        arguments:
          parameters: [{name: message, value: Extract Data}]
          
    - - name: nrun-amlp
        template: run-amlp
        arguments:
          parameters:
            - name: args
              value: run amlp

      - name: nrun-rust-ml
        template: run-rust-ml
        arguments:
          parameters:
            - name: args
              value: run rust 

      - name: nrun-autosklearn
        template: run-autosklearn

      - name: nrun-r-ml
        template: run-r-ml
