apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sequential-
spec:
  entrypoint: run-preprocessing
  arguments:
    parameters:
    - name: args
      value: run preprocessing
  templates:
  - name: run-rust-ml
    inputs:
      parameters:
      - name: args       # parameter declaration
    container:
      image: ppalmes/rust-ml:latest
      command: ["automl"]
      args: ["{{inputs.parameters.args}}"]

  - name: echo
    inputs:
      parameters:
        - name: message
    container:
      image: alpine:3.7
      command: [echo,"{{inputs.parameters.message}}"]

  - name: run-preprocessing
    inputs:
      parameters:
      - name: args       # parameter declaration
    steps:
    - - name: Imputation
        template: echo
        arguments:
          parameters: [{name: message, value: Imputation}]
    - - name: Normalization
        template: echo
        arguments:
          parameters: [{name: message, value: Normalization}]
    - - name: FeatureExtraction
        template: echo
        arguments:
          parameters: [{name: message, value: FeatureExtraction}]
    - - name: FeatureEngineering
        template: echo
        arguments:
          parameters: [{name: message, value: FeatureEngineering}]
    - - name: nrun-rust-ml
        template: run-rust-ml
        arguments:
          parameters:
            - name: args
              value: run rust 
